--liquibase formatted sql

--changeset sobornov:1
CREATE TABLE tasks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    status      VARCHAR(20)  NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    deadline    TIMESTAMP    NOT NULL,
    finished_at TIMESTAMP
);

--changeset sobornov:2
ALTER TABLE tasks ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
